export type RootStackParamList = {
  Welcome: undefined;
  ReferralOnboarding: undefined;
  PainPoint: undefined;
  PainPoint2: undefined;
  PainPoint3: undefined;
  PersonalizationTransition: undefined;
  Onboarding: undefined;
  AIGeneration: undefined;
  PlanReady: undefined;
  EffectivenessComparison: undefined;
  SuccessRate: undefined;
  ResultsTimeline: undefined;
  Rating: undefined;
  Feedback: undefined;
  Commitment: undefined;
  FinalCommit: undefined;
  InviteReferral: undefined;
  Paywall: undefined;
  Home: undefined;
  NoteEditor: { noteId?: string };
  Feynman: { noteId: string };
  Search: undefined;
  Settings: undefined;
  Referral: undefined;
  BackendTest: undefined;
  ContentSource: undefined;
  AudioRecorder: undefined;
  YouTubeInput: undefined;
  DocumentUpload: undefined;
  TextInput: undefined;
  LinkInput: undefined;
  VoiceAssistant: undefined;
  ScreenshotOCR: undefined;
  LearningPath: undefined;
  AudioTimestamp: { noteId: string };
};
